[features]
seeds = false

# giving Anchor the programID, public key of solana-twitter program
[programs.localnet]
solana_twitter = "8GNkUvrrk8b2qgVxfaB7QHPgiA7qgzGer4jaoZ2fqUyn"
[programs.devnet]
solana_twitter = "8GNkUvrrk8b2qgVxfaB7QHPgiA7qgzGer4jaoZ2fqUyn"
# Normally fine, BUT wouldn't want to have the same one on mainnet as it allows people to access target/deploy/solana_twitter-keypair.json with keypair values
[programs.mainnet]
solana_twitter = "8GNkUvrrk8b2qgVxfaB7QHPgiA7qgzGer4jaoZ2fqUyn"

[registry]
url = "https://anchor.projectserum.com"

# telling Anchor to use the localnet/devnet/mainnet cluster and where to find the wallet used for transactions
[provider]
cluster = "devnet"
wallet = "/home/mfunakoshi98/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
# makes sure app/src/idl exists, then copies the IDL file inside it.
copy-idl = "mkdir -p app/src/idl && cp target/idl/solana_twitter.json app/src/idl/solana_twitter.json"